<a href="https://colab.research.google.com/github/abhishektyagi0020/Python-files/blob/main/Numpylib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**

1.NumPy is a Python library.
  It is used for working with arrays.
  It is short for "Numerical Python".
  It is used for computation and processing of single and multi dimensional array of eleme
  Smaller memory consumption and better runtime behavior.



In [17]:
pip install numpy

In [18]:
import numpy as np #here import library numpy


In [20]:
values=[102.4,.56,.675,67.78]

In [21]:
arr=np.array(values)

In [22]:
print(arr)

[102.4     0.56    0.675  67.78 ]


In [23]:
print(arr+200)

[302.4   200.56  200.675 267.78 ]


In [24]:
a=np.array([10,23,45])
#array create using library of numpy

In [25]:
print(a)

[10 23 45]


In [26]:
#create 2d array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)


[[1 2 3]
 [4 5 6]]


In [27]:
#if mentioned array datatypes str= string , float, int
b = np.array([[1, 2, 3], [4, 5, 6]], dtype=str)
print(b)


[['1' '2' '3']
 ['4' '5' '6']]


In [28]:
type(b) #just check array types

numpy.ndarray

In [29]:
len(b) #length showsrows int array or element s


2

In [30]:
# 3d array
c=np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=int)

In [31]:
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
#check dimesnssion of array -> arrayname.ndim
c.ndim

2

Why Use NumPy?

   In Traditional Python Programming, we have lists that serve the purpose of arrays, but they are slow to process.
   NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
   The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with indarray ver
   easy.
   Arrays are very frequently used in data science, where speed and resources are very important.


In [33]:
c.shape # shape check row or column in matrix or array

(3, 3)

In [34]:
c.dtype


dtype('int64')